### ISSUE TITLE
target .bed is malformed 

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/GenomeKey2#4]
target.bed is malformed: Problem reading the interval file caused by Badly formed genome loc: Contig chr22 given as location, but this contig isn't present in the Fasta sequence dictionary

Is there a way to check the .bed file for proper formatting before running? 
Is this a b37 Vs hg19 annotation issue?

**Comment by egafni** [comment]
Yeah, that would be a straightforward assertion - you can get the contig names from the reference fasta, and the contig names from the target_bed and ensure that target_bed is a subset of the reference fasta.  I'm a big fan of fail-fast assertions like that, and if you want to add it to GenomeKey, you could make a branch off of develop and do a pull request

It's not a b37 vs hg19 - the difference there is that b37 contains genome patches (a bunch of extra contigs with sequences that NCBI was unable to assemble into the genome)

it's probably because your bed file has 'chr' appended before the number - ie it should just be '1' not 'chr1'

**Comment by Double-O-ren** [comment]
I removed the chr on all lines of the bed and it worked fine

**Comment by yassineS** [comment]
Just removing 'chr' will not solve the problem, as @egafni mentioned the two builds aren't exactly the same and doing simple conversion like this will carry issues down the line. 

You need to use UCSC [liftOver](https://genome-store.ucsc.edu) to convert between the two reference genome builds. You will need the chain file `hg19tob37.chain` provided by GATK to do so, you can get it from GATK's ftp: ftp://ftp.broadinstitute.org/Liftover_Chain_Files/

For more details you can take a look at the two following threads:
http://gatkforums.broadinstitute.org/discussion/6092/vcf-liftover-question
https://www.biostars.org/p/101543/

**Comment by egafni** [comment]
@yassineS liftover is not necessary.  The main chromosomes have identical coordinates, the only differences are the patches and 'chr' being prepended

**Comment by Double-O-ren** [comment]
Are there significant differences between SNPs, indels and SVs that the patches of b37 capture and hg19 don't? Besides the documented M chromosome?

**Comment by Double-O-ren** [comment]
I also removed the top two rows, they had some sort of malformed header

**Comment by egafni** [comment]
I'm pretty sure hg19 just simply doesn't have the patches (there's a lot going on in those things)
